# golangci-lint configuration v2
# Run with: golangci-lint run ./...
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  # Explicitly enable linters (don't use defaults to avoid errcheck noise)
  default: none
  enable:
    - govet         # Report suspicious constructs
    - ineffassign   # Detect unused assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - misspell      # Find common spelling mistakes
    - unconvert     # Remove unnecessary type conversions

  # Settings for individual linters (moved from root linters-settings)
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too strict for existing codebase
        - shadow          # Too many false positives

    staticcheck:
      checks:
        - all
        - -SA1019  # Ignore deprecated warnings

    misspell:
      locale: US

formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check imports

  settings:
    goimports:
      local-prefixes:
        - github.com/mescon/Healarr

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
