coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        # Lowered to 65% to accommodate error handling paths that are
        # difficult to test (rows.Err(), event bus publish errors, etc.)
        # These are edge cases that require complex mocking and rarely occur
        target: 65%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  backend:
    paths:
      - cmd/
      - internal/
    carryforward: true

ignore:
  - "**/*_test.go"
  - "**/testutil/**"
  - "frontend/**"
  - "web/**"
